name: Docs

on:
  workflow_dispatch:
    inputs:
      python-version:
        type: string
        default: "3.12"
      working-directory:
        type: string
        default: "."
      mkdocs-config:
        type: string
        default: "mkdocs.yml"
      uv-sync-args:
        type: string
        default: ""
      mkdocs-args:
        type: string
        default: ""

jobs:
  deploy-docs:
    permissions:
      contents: write
    uses: ./.github/workflows/docs-deploy.yml
    with:
      python-version: ${{ inputs.python-version }}
      working-directory: ${{ inputs.working-directory }}
      mkdocs-config: ${{ inputs.mkdocs-config }}
      uv-sync-args: ${{ inputs.uv-sync-args }}
      mkdocs-args: ${{ inputs.mkdocs-args }}
